[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=\U0001F579 韩国游戏,https://raw.githubusercontent.com/FedHoo/IP-TEST/main/%E9%9F%A9%E5%9B%BD%E6%B8%B8%E6%88%8F.list?token=GHSAT0AAAAAACVBMWD7ASVGP2BNUKXLKIYKZU6FBQQ
ruleset=🇸🇬 PikPak,https://raw.githubusercontent.com/FedHoo/IP-TEST/main/PikPak.list?token=GHSAT0AAAAAACVBMWD6GAS47ZFHPRDY7FESZU6FAWQ
ruleset=\U0001F48E 自动选择,https://raw.githubusercontent.com/FedHoo/IP-TEST/main/%E8%87%AA%E5%8A%A8%E9%80%89%E6%8B%A9.list?token=GHSAT0AAAAAACVBMWD7S5KTROP6DMZRWW4EZU5NKLQ
ruleset=\U0001F4E8 Google Series,https://raw.githubusercontent.com/FedHoo/IP-TEST/main/Google.list?token=GHSAT0AAAAAACVBMWD6SKJ76JNG4LTXFJEGZU5NJMA
ruleset=\U0001F5A5 苹果服务,https://raw.githubusercontent.com/FedHoo/IP-TEST/main/%E8%8B%B9%E6%9E%9C%E6%9C%8D%E5%8A%A1.list?token=GHSAT0AAAAAACVBMWD6F2F5FZFHPS5HJEIQZU5NK2A
ruleset=\U0001F4BF Telegram,https://raw.githubusercontent.com/FedHoo/IP-TEST/main/%E7%94%B5%E6%8A%A5%E4%BF%A1%E6%81%AF.list?token=GHSAT0AAAAAACVBMWD64LBCSE37XZD3WBCQZU5NNQA
ruleset=\U0001F4FD 国外媒体,https://raw.githubusercontent.com/FedHoo/IP-TEST/main/%E5%9B%BD%E5%A4%96%E5%AA%92%E4%BD%93.list?token=GHSAT0AAAAAACVBMWD6T543JH3DSB2DEKCUZU5NLMQ
ruleset=\U0001F4BE 国内媒体,https://raw.githubusercontent.com/FedHoo/IP-TEST/main/%E5%9B%BD%E5%86%85%E5%AA%92%E4%BD%93.list?token=GHSAT0AAAAAACVBMWD7GBWWVX3WWCX5VOMQZU5NLYA
ruleset=\U0001F4E1 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=\U0001F4E1 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=\U0001F6AB 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=\U0001F4E8 Google Series,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=\U0001F4E1 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=\U0001F4E1 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=\U0001F4FA 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=\U0001F4FA 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=\U0001F4FA 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=\U0001F5A5 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=\U0001F4BF Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🎶 网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=📹 Youtube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=\U0001F4FD 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=\U0001F4FD 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=✏️ 手动选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=✏️ 手动选择,https://raw.githubusercontent.com/UlinoyaPed/ShellClash/dev/lists/proxy.list
ruleset=✏️ 手动选择,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/CMBlog.list
ruleset=\U0001F4E1 全球直连,https://raw.githubusercontent.com/UlinoyaPed/ShellClash/dev/lists/direct.list
;ruleset=\U0001F4E1 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=\U0001F4E1 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=\U0001F4E1 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=\U0001F4E1 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=\U0001F4E1 全球直连,[]GEOIP,LAN
ruleset=\U0001F4E1 全球直连,[]GEOIP,CN
ruleset=🍃 应用净化,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/adobe.list
ruleset=\U0001F433 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=✏️ 手动选择`select`.*
custom_proxy_group=\U0001F48E 自动选择`url-test`[]🇭🇰 香港`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇰🇷 韩国`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=\U0001F4BF Telegram`select`[]✏️ 手动选择`[]\U0001F48E 自动选择`
custom_proxy_group=📹 Youtube`select`[]✏️ 手动选择`[]\U0001F48E 自动选择`[]🇭🇰 香港`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国
custom_proxy_group=📺 哔哩哔哩`select`[]\U0001F4E1 全球直连
custom_proxy_group=\U0001F4FD 国外媒体`select`[]✏️ 手动选择`[]\U0001F48E 自动选择`[]🇭🇰 香港`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇹🇼 台湾`[]🇰🇷 韩国
custom_proxy_group=\U0001F4FD 国内媒体`select`[]DIRECT
custom_proxy_group=\U0001F4E8 Google Series`select`[]✏️ 手动选择`[]\U0001F48E 自动选择`[]🇭🇰 香港`[]🇸🇬 新加坡`[]🇺🇲 美国
custom_proxy_group=\U0001F4FA 微软服务`select`[]✏️ 手动选择`[]DIRECT
custom_proxy_group=\U0001F5A5 苹果服务`select`[]✏️ 手动选择`[]DIRECT`[]🇭🇰 香港`[]🇺🇲 美国
custom_proxy_group=🎶 网易音乐`select`[]\U0001F4E1 全球直连
custom_proxy_group=🇸🇬 PikPak`url-test`[]🇭🇰 香港`[]🇸🇬 新加坡`[]🇯🇵 日本`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=\U0001F579 韩国游戏`url-test`[]🇰🇷 韩国`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=\U0001F4E1 全球直连`select`[]DIRECT
custom_proxy_group=\U0001F6AB 全球拦截`select`[]REJECT
custom_proxy_group=🍃 应用净化`select`[]REJECT
custom_proxy_group=\U0001F433 漏网之鱼`select`[]✏️ 手动选择`[]\U0001F48E 自动选择


custom_proxy_group=🇭🇰 香港`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong|HKG)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|Tokyo|NRT|KIX)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇹🇼 台湾`url-test`(台|新北|彰化|TW|Taiwan|TPE|KHH)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡`url-test`(新加坡|坡|狮城|SG|Singapore|SIN)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国`url-test`(KR|Korea|KOR|Seoul|首尔|春川|韩|韓|ICN)`http://www.gstatic.com/generate_204`300,,50
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
